name: Master workflow

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish_in_dockerhub_and_git_registry:
    name: Publish in DockerHub and GitHub Registry
    runs-on: ubuntu-20.04
    env:
      PULL_IMAGE_NAME: items:rc
      PUSH_IMAGE_NAME: items
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Pull image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/$PULL_IMAGE_NAME
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" 
      - name: Run test in docker
        run: docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/$PULL_IMAGE_NAME ./mvnw test
      - name: Push image to DockerHub tag:version
        run: |
          IMAGE_VERSION=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/$PULL_IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME }}/$PUSH_IMAGE_NAME:$IMAGE_VERSION
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$PUSH_IMAGE_NAME:$IMAGE_VERSION
          
      - name: Login to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image to GitHub Container Registry tag:version
        run: |
          IMAGE_VERSION=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)
          IMAGE_USER=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/$PULL_IMAGE_NAME ghcr.io/$IMAGE_USER/$PUSH_IMAGE_NAME:$IMAGE_VERSION
          docker push ghcr.io/$IMAGE_USER/$PUSH_IMAGE_NAME:$IMAGE_VERSION
